---
kind: pipeline
name: python-3.5

steps:
- name: test
  image: python:3.5
  commands:
  - VIRTUAL_ENV=1 utils/run_tests.sh
---
kind: pipeline
name: python-3.6

steps:
- name: test
  image: python:3.6
  commands:
  - VIRTUAL_ENV=1 utils/run_tests.sh
---
kind: pipeline
name: python-3.7

steps:
- name: test
  image: python:3.7
  commands:
  - VIRTUAL_ENV=1 utils/run_tests.sh
---
kind: pipeline
name: python-3.8

steps:
- name: test
  image: python:3.899
  commands:
  - VIRTUAL_ENV=1 utils/run_tests.sh
