---
kind: pipeline
name: python-3.6

steps:
- name: test
  image: python:3.6
  commands:
  - VIRTUAL_ENV=1 MODULE=tomatic bash tools/run_tests.sh
---
kind: pipeline
name: python-3.7

steps:
- name: test
  image: python:3.7
  commands:
  - VIRTUAL_ENV=1 MODULE=tomatic bash tools/run_tests.sh
---
kind: pipeline
name: python-3.8

steps:
- name: test
  image: python:3.8
  commands:
  - VIRTUAL_ENV=1 MODULE=tomatic bash tools/run_tests.sh
